name: Build and test on Wokwi

on:
  workflow_dispatch:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install PlatformIO Core
        run: pip install -U https://github.com/Jason2866/platformio-core/archive/rm_telemetry.zip

      - name: Build PlatformIO Project
        run: pio run

      - name: Test with Wokwi
        uses: wokwi/wokwi-ci-action@v1
        with:
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          scenario: 'http-client.test.yaml'
          timeout: 10000
